### ISSUE TITLE
Which version of Visual Studio do you use to compile this code?

### ISSUE THREAD

**Issue by dickinsonre** [OOW/SWMMout2csv#6]
Hello, I am using ViS 2012 and have a problem with your vector statements

for example, this line

	vector<string> names{ "extract Subcatchments","extract Nodes","extract Links", "extract System" };

which has this build error 

1>SWMMout2csv.cpp(232): error C2601: 'names' : local function definitions are illegal
1>          SWMMout2csv.cpp(205): this line contains a '{' which has not yet been matched

Thanks, 
Bob Dickinson

**Comment by edwardlennonjr** [comment]
I complied this code with the x64 Release settings using; 
Microsoft Visual Studio Community 2015
Version 14.0.25420.1
https://github.com/OOW/SWMMout2csv/blob/master/SWMMout2csv.sln

line 232: local function definitions are illegal; I guess in newer versions this is now legal.  
line 205: this line contains a '{' which has not yet been matched; I can't find an error in curly braces here, and I'm fairly sure this error is an after effect of the first error.


The current version I have installed is Version 14.0.25431.01 Update 3

When I recomplied I got the following warnings, which need to be addressed...;
  stdafx.cpp
  SWMMout2csv.cpp
SWMMout2csv.cpp(336): warning C4101: 'e': unreferenced local variable
SWMMout2csv.cpp(474): warning C4129: '.': unrecognized character escape sequence
SWMMout2csv.cpp(718): warning C4018: '<=': signed/unsigned mismatch
SWMMout2csv.cpp(1068): warning C4018: '<=': signed/unsigned mismatch
